#!/bin/bash
# Финальная подготовка к развертыванию

echo "✅ Структура Infrastructure готова!"
echo ""
echo "📁 Созданные файлы:"
echo "  ├── ansible.cfg - Конфигурация Ansible"
echo "  ├── inventory.yml - Инвентарь хостов"
echo "  ├── deploy.yml - Playbook развертывания"
echo "  ├── roles/"
echo "  │   ├── docker/ - Установка Docker"
echo "  │   ├── project/ - Развертывание проекта"
echo "  │   └── ssl/ - SSL сертификаты"
echo "  ├── group_vars/ - Переменные групп"
echo "  ├── host_vars/ - Переменные хостов"
echo "  └── scripts/ - Вспомогательные скрипты"
echo ""
echo "🚀 Следующие шаги:"
echo ""
echo "1️⃣  Подготовка SSH:"
echo "   cd infrastructure"
echo "   bash scripts/setup_ssh.sh"
echo ""
echo "2️⃣  Настройка инвентаря:"
echo "   nano inventory.yml"
echo "   # Установите правильные IP адреса хостов"
echo ""
echo "3️⃣  Настройка переменных:"
echo "   nano host_vars/production.yml"
echo "   # Заполните переменные для production"
echo ""
echo "4️⃣  Тест развертывания:"
echo "   bash scripts/test_deploy.sh localhost_dev"
echo ""
echo "5️⃣  Развертывание:"
echo "   bash scripts/deploy.sh production"
echo ""
echo "6️⃣  Проверка здоровья:"
echo "   bash scripts/health_check.sh production"
echo ""
echo "📖 Дополнительная информация:"
echo "   - QUICKSTART.md - Быстрый старт"
echo "   - README.md - Полная документация"
echo ""
